//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public int id { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public Nullable<int> dias_totales { get; set; }
        public int vehiculoID { get; set; }
        public int estado { get; set; }
        public int total { get; set; }
        public string userID { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
