//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Orden = new HashSet<Orden>();
        }
    
        public int id { get; set; }
        public int categoriaID { get; set; }
        public string modelo { get; set; }
        public int capacidad { get; set; }
        public string transmision { get; set; }
        public bool aire_acondicionado { get; set; }
        public bool cierre_centralizado { get; set; }
        public int abono { get; set; }
        public int valor { get; set; }
        public string url_foto { get; set; }
        public bool disponible { get; set; }
        public int puertas { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Orden { get; set; }
    }
}
